name: Trigger auto deployment for littlebig-core-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/littlebig-core-backend-AutoDeployTrigger-96bd7714-d799-4aec-9a99-3435ddcbb46f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LITTLEBIGCOREBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LITTLEBIGCOREBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LITTLEBIGCOREBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.LITTLEBIGCOREBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LITTLEBIGCOREBACKEND_REGISTRY_PASSWORD }}
          containerAppName: littlebig-core-backend
          resourceGroup: littlebigdemo
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


